package com.mikolove.allmightworkout.framework.datasource.database

const val WORKOUT_ORDER_ASC: String = ""
const val WORKOUT_ORDER_DESC: String = "-"
const val WORKOUT_FILTER_NAME = "name"
const val WORKOUT_FILTER_DATE_CREATED = "createdAt"

const val WORKOUT_ORDER_BY_ASC_DATE_UPDATED = WORKOUT_ORDER_ASC + WORKOUT_FILTER_DATE_CREATED
const val WORKOUT_ORDER_BY_DESC_DATE_UPDATED = WORKOUT_ORDER_DESC + WORKOUT_FILTER_DATE_CREATED
const val WORKOUT_ORDER_BY_ASC_NAME = WORKOUT_ORDER_ASC + WORKOUT_FILTER_NAME
const val WORKOUT_ORDER_BY_DESC_NAME = WORKOUT_ORDER_DESC + WORKOUT_FILTER_NAME

const val WORKOUT_PAGINATION_PAGE_SIZE = 30