package dependencies

object Versions {
    val gradle = "4.1.2"
    val compilesdk = 30
    val minsdk = 16
    val targetsdk = 30
    val kotlin = "1.4.21"
    val ktx = "1.3.1"
    val hilt = "2.31.2-alpha"
    val hilt_testing = "2.31.2-alpha"
    val hilt_jetpack = "1.0.0-alpha03"
    val nav_components = "2.3.0"
    val material_dialogs = "3.3.0"
    val room = "2.2.5"
    val appcompat = "1.2.0"
    val constraintlayout = "2.0.0"
    val material_design = "1.2.1"
    val play_core = "1.8.0"
    val play_services = "4.3.4"
    val build_firebase_crashlytics = "2.3.0"
    val leak_canary = "2.4"
    val swipe_refresh_layout = "1.1.0-alpha03"
    val firebase_firestore = "21.6.0"
    val firebase_analytics = "17.5.0"
    val firebase_crashlytics = "2.10.1"
    val firebase_auth = "19.4.0"
    val firebase_bom = "25.12.0"
    val espresso_core = "3.3.0"
    val espresso_idling_resource = "3.3.0"
    val mockk_version = "1.9.2"
    val test_runner = "1.2.0"
    val test_core = "1.2.0"
    val coroutines_version = "1.4.1"
    val coroutines_play_services = "1.3.2"
    val lifecycle_version = "2.3.0-alpha07"
    val retrofit2_version = "2.9.0"
    val markdown_processor = "0.1.3"
    val junit_jupiter_version = "5.7.0"
    val junit_4_version = "4.13"
    val fragment_version = "1.3.0-alpha08"
    val androidx_test_ext = "1.1.2"
    val multidex_version = "2.0.1"
    //val fragment_test = "1.3.0-alpha06"
}